$N = 8$ のとき，複素正弦波信号 $\phi_k[n] = e^{j 2 \pi k n / N}, \quad k = 0, 1, \cdots, N-1$ 間の内積
$\langle \phi_k, \phi_l \rangle$ を計算し， $\langle \phi_k, \phi_l \rangle$ を $k$ 行 $l$ 列の要素とする行列を作りなさい．
この行列から $\phi_0, \cdots, \phi_{N-1}$ が互いに直交していることを確認しなさい．

In [3]:

import numpy as np

a = 2j
print(a)
b = a**2
print(b)

2j
(-4+0j)


In [1]:
import numpy as np

N = 8
G = np.zeros((N, N), dtype=complex)

for k in range(N):
    for l in range(N):
        n = np.arange(N)
        phi_k = np.exp(1j * 2 * np.pi * k * n / N)
        phi_l = np.exp(1j * 2 * np.pi * l * n / N)
        G[k, l] = np.sum(phi_k * np.conj(phi_l))

print(np.round(G.real).astype(int))

[[8 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0]
 [0 0 8 0 0 0 0 0]
 [0 0 0 8 0 0 0 0]
 [0 0 0 0 8 0 0 0]
 [0 0 0 0 0 8 0 0]
 [0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 8]]
