2次元DFTが1次元DFTを行方向・列方向に順に適用したものと一致することを確認する．
適当な $8 \times 8$ の2次元信号に対して，```np.fft.fft``` を ```axis=1```（行方向），続いて ```axis=0```（列方向）に適用した結果と，
```np.fft.fft2``` の結果が一致することを ```np.allclose``` で確認しなさい．


In [1]:
import numpy as np

# 8×8 の2次元信号
x = np.arange(64).reshape(8, 8).astype(float)

# 1次元DFTを行方向 axis=1 に適用
X_row = np.fft.fft(x, axis=1)

# 続いて列方向 axis=0 に適用
X_seq = np.fft.fft(X_row, axis=0)

# 2次元DFT
X_fft2 = np.fft.fft2(x)

# 一致確認
result = np.allclose(X_seq, X_fft2)

# 最大誤差
max_error = np.max(np.abs(X_seq - X_fft2))

print("x =")
print(x)

print("np.allclose(X_seq, X_fft2) =", result)
print("max error =", max_error)

x =
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29. 30. 31.]
 [32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47.]
 [48. 49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62. 63.]]
np.allclose(X_seq, X_fft2) = True
max error = 0.0
